import { SidebarServer } from "@/components/sidebar-server";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | Coffee Mania",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex p-2 w-full min-h-screen  bg-default-50 dark:bg-default-950">
      <SidebarServer />
      <main className="flex-1 p-2">{children}</main>
    </main>
  );
}
